/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartkost;

/**
 *
 * @author user
 */
public class BERANDA extends javax.swing.JFrame {

    /**
     * Creates new form BERANDA
     */
    public BERANDA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        txtJumlahPemasukkan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJenisPengeluaran = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BKurang = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtJenisPemasukkan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtJumlahPengeluaran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setText("SMARTKOST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 230, 60));

        jLabel2.setText("Saldo Anda :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 137, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 90, 50));

        txtJumlahPemasukkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahPemasukkanActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlahPemasukkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 320, 30));

        jLabel3.setText("Pemasukkan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 90, 30));

        jLabel4.setText("Pengeluaran");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        txtJenisPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisPengeluaranActionPerformed(evt);
            }
        });
        getContentPane().add(txtJenisPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 320, 30));

        BTambah.setText("+");
        getContentPane().add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        BKurang.setText("-");
        BKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKurangActionPerformed(evt);
            }
        });
        getContentPane().add(BKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        jLabel5.setText("\"Budget Terjaga, Hidup Kost Bahagia!\"");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtJenisPemasukkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisPemasukkanActionPerformed(evt);
            }
        });
        getContentPane().add(txtJenisPemasukkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 320, 30));

        jLabel6.setText("Nama");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        jLabel7.setText("Jumlah");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));
        getContentPane().add(txtJumlahPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 320, 30));

        jLabel8.setText("Nama");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel9.setText("Jumlah");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 320, 910, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 320, 870, 20));

        BDetail.setText("Detail");
        BDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDetailActionPerformed(evt);
            }
        });
        getContentPane().add(BDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, -1, -1));

        setSize(new java.awt.Dimension(862, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahPemasukkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahPemasukkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahPemasukkanActionPerformed

    private void txtJenisPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisPengeluaranActionPerformed

    private void BKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKurangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BKurangActionPerformed

    private void txtJenisPemasukkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisPemasukkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisPemasukkanActionPerformed

    private void BDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDetailActionPerformed
        // TODO add your handling code here:
        RINCIAN RINCIAN = new RINCIAN();
                RINCIAN.setVisible(true);
    }//GEN-LAST:event_BDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BERANDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BERANDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BERANDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BERANDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BERANDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDetail;
    private javax.swing.JButton BKurang;
    private javax.swing.JButton BTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField txtJenisPemasukkan;
    private javax.swing.JTextField txtJenisPengeluaran;
    private javax.swing.JTextField txtJumlahPemasukkan;
    private javax.swing.JTextField txtJumlahPengeluaran;
    // End of variables declaration//GEN-END:variables
}
